#!/usr/bin/env bash
# 新机器一键恢复 Codex 个人配置
# 用法: ~/codex-setup/bootstrap.sh
#
# 你只需要改 settings.json / .env（和 claude-setup 一样），
# 本脚本会生成 Codex 运行时需要的 ~/.codex/config.toml。

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CODEX_HOME="${CODEX_HOME:-${HOME}/.codex}"
AGENTS_SKILLS="${HOME}/.agents/skills"
REAL_CODEX_CANDIDATES=(
  "${HOME}/codex/node_modules/.bin/codex"
  "${HOME}/.npm-global/bin/codex"
  "${HOME}/.local/node/bin/codex"
  "${HOME}/codex/bin/codex"
)

read_lock_file() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  grep -v '^\s*#' "$file" | grep -v '^\s*$' || true
}

codex_has_plugin_cli() {
  "${REAL_CODEX}" plugin --help >/dev/null 2>&1
}

log()  { echo "[codex-setup] $*"; }
warn() { echo "[codex-setup] WARNING: $*" >&2; }
die()  { echo "[codex-setup] ERROR: $*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "缺少命令: $1"
}

is_setup_wrapper() {
  local path="$1"
  [[ -f "$path" ]] && grep -q 'codex-setup wrapper' "$path" 2>/dev/null
}

find_real_codex() {
  local candidate
  for candidate in "${REAL_CODEX_CANDIDATES[@]}"; do
    [[ -e "$candidate" ]] || continue
    is_setup_wrapper "$candidate" && continue
    if [[ -x "$candidate" ]] || [[ -L "$candidate" ]]; then
      echo "$candidate"
      return 0
    fi
  done
  if command -v codex >/dev/null 2>&1; then
    candidate="$(command -v codex)"
    if ! is_setup_wrapper "$candidate"; then
      echo "$candidate"
      return 0
    fi
  fi
  return 1
}

install_wrapper() {
  local real_codex="$1"
  local wrapper="${HOME}/.local/bin/codex"
  mkdir -p "${HOME}/.local/bin"

  cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# codex-setup wrapper — loads API key then exec real Codex
set -euo pipefail
REPO="${REPO}"
REAL_CODEX="${real_codex}"

load_env() {
  local f="\$1"
  [[ -f "\$f" ]] || return 0
  set -a
  # shellcheck disable=SC1090
  source "\$f"
  set +a
}

load_env "\${REPO}/.env"
load_env "\${HOME}/claude-setup/.env"

if [[ -z "\${OPENAI_API_KEY:-}" && -n "\${ANTHROPIC_AUTH_TOKEN:-}" ]]; then
  export OPENAI_API_KEY="\${ANTHROPIC_AUTH_TOKEN}"
fi

exec "\${REAL_CODEX}" "\$@"
EOF
  chmod +x "$wrapper"
  log "已安装 PATH 包装器: ${wrapper} -> ${real_codex}"
}

# settings.json (+ MCP JSON) -> ~/.codex/config.toml
render_config_toml() {
  local settings_file="${REPO}/settings.json"
  local mcp_file="${REPO}/mcp/user-servers.json"
  local out_file="${CODEX_HOME}/config.toml"

  [[ -f "$settings_file" ]] || die "缺少 ${settings_file}"

  local resolved_mcp
  resolved_mcp="$(mktemp)"
  if [[ -f "$mcp_file" ]]; then
    if command -v envsubst >/dev/null 2>&1; then
      export HOME
      envsubst < "$mcp_file" > "$resolved_mcp"
    else
      cp "$mcp_file" "$resolved_mcp"
    fi
  else
    echo '{"mcpServers":{}}' > "$resolved_mcp"
  fi

  python3 - "$settings_file" "$resolved_mcp" "$out_file" <<'PY'
import json, sys
from pathlib import Path

settings_path, mcp_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
settings = json.loads(Path(settings_path).read_text(encoding="utf-8"))
mcp = json.loads(Path(mcp_path).read_text(encoding="utf-8"))
env = settings.get("env") or {}

base_url = env.get("OPENAI_BASE_URL") or "https://vip.auto-code.net/v1"
model = env.get("OPENAI_MODEL") or "gpt-5.5"
# 兼容误把 Claude 字段写进本仓库的情况
if not env.get("OPENAI_MODEL") and env.get("ANTHROPIC_MODEL"):
    model = env["ANTHROPIC_MODEL"]
if not env.get("OPENAI_BASE_URL") and env.get("ANTHROPIC_BASE_URL"):
    base = env["ANTHROPIC_BASE_URL"].rstrip("/")
    base_url = base if base.endswith("/v1") else base + "/v1"

def toml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

lines = [
    "# Generated by codex-setup/bootstrap.sh from settings.json — do not edit by hand",
    f"model = {toml_str(model)}",
    'model_provider = "auto-code"',
    'approval_policy = "on-request"',
    'sandbox_mode = "workspace-write"',
    "",
    "[model_providers.auto-code]",
    'name = "Auto-Code"',
    f"base_url = {toml_str(base_url)}",
    'env_key = "OPENAI_API_KEY"',
    'wire_api = "responses"',
    "requires_openai_auth = false",
]

servers = mcp.get("mcpServers") or {}
for name, cfg in servers.items():
    lines.append("")
    lines.append(f"[mcp_servers.{name}]")
    if cfg.get("url"):
        lines.append(f"url = {toml_str(cfg['url'])}")
        if cfg.get("bearer_token_env_var"):
            lines.append(f"bearer_token_env_var = {toml_str(cfg['bearer_token_env_var'])}")
        continue
    if cfg.get("command"):
        lines.append(f"command = {toml_str(cfg['command'])}")
    args = cfg.get("args") or []
    if args:
        rendered = ", ".join(toml_str(a) for a in args)
        lines.append(f"args = [{rendered}]")
    env_map = cfg.get("env") or {}
    if env_map:
        lines.append(f"[mcp_servers.{name}.env]")
        for k, v in env_map.items():
            lines.append(f"{k} = {toml_str(str(v))}")

Path(out_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"model={model}")
print(f"base_url={base_url}")
print(f"mcp_servers={len(servers)}")
PY
  rm -f "$resolved_mcp"
}

# --- 前置检查 ---

require_cmd jq
require_cmd python3
if ! command -v envsubst >/dev/null 2>&1; then
  warn "未找到 envsubst，MCP 配置中的 \${VAR} 将不会被展开（可安装 gettext 包）"
fi

REAL_CODEX="$(find_real_codex)" || die "未找到 Codex 可执行文件。请先安装: npm install --prefix ~/codex @openai/codex@latest"
log "Codex 二进制: ${REAL_CODEX}"
CODEX_VERSION="$("${REAL_CODEX}" --version 2>/dev/null | head -1 || true)"
log "Codex 版本: ${CODEX_VERSION:-unknown}"
"${REAL_CODEX}" --version >/dev/null 2>&1 || die "Codex 无法运行: ${REAL_CODEX}"

mkdir -p "${CODEX_HOME}" "${AGENTS_SKILLS}"

# 加载环境变量（密钥）
if [[ -f "${REPO}/.env" ]]; then
  log "加载 ${REPO}/.env"
  set -a
  # shellcheck disable=SC1091
  source "${REPO}/.env"
  set +a
fi

if [[ -f "${HOME}/claude-setup/.env" ]]; then
  log "加载 ${HOME}/claude-setup/.env（可复用 API Key）"
  set -a
  # shellcheck disable=SC1091
  source "${HOME}/claude-setup/.env"
  set +a
fi

if [[ -z "${OPENAI_API_KEY:-}" && -n "${ANTHROPIC_AUTH_TOKEN:-}" ]]; then
  export OPENAI_API_KEY="${ANTHROPIC_AUTH_TOKEN}"
  log "已将 ANTHROPIC_AUTH_TOKEN 映射为 OPENAI_API_KEY"
fi

if [[ -z "${OPENAI_API_KEY:-}" ]]; then
  warn "未设置 OPENAI_API_KEY。请: cp ${REPO}/.env.example ${REPO}/.env 并填入密钥"
fi

# --- 1. PATH 包装器 ---

install_wrapper "${REAL_CODEX}"
export PATH="${HOME}/.local/bin:${PATH}"

# --- 2. settings.json -> ~/.codex/config.toml ---

log "从 settings.json 生成 ${CODEX_HOME}/config.toml"
render_info="$(render_config_toml)"
log "  ${render_info//$'\n'/ | }"

# --- 3. AGENTS.md ---

if [[ -f "${REPO}/AGENTS.md" ]]; then
  log "同步 AGENTS.md -> ${CODEX_HOME}/AGENTS.md"
  cp "${REPO}/AGENTS.md" "${CODEX_HOME}/AGENTS.md"
fi

# --- 4. Skills ---

log "链接独立 Skills..."
skill_count=0
for skill_dir in "${REPO}"/skills/*/; do
  [[ -d "$skill_dir" ]] || continue
  name="$(basename "$skill_dir")"
  [[ "$name" == "README.md" ]] && continue
  if [[ ! -f "${skill_dir}/SKILL.md" ]]; then
    warn "  跳过 ${name}：缺少 SKILL.md"
    continue
  fi
  ln -sfn "$skill_dir" "${AGENTS_SKILLS}/${name}"
  log "  skill linked: ${name}"
  skill_count=$((skill_count + 1))
done
log "  共链接 ${skill_count} 个 skill"

# --- 5. Marketplace / Plugin ---

if codex_has_plugin_cli; then
  log "添加 Marketplace..."
  while IFS= read -r source; do
    [[ -z "$source" ]] && continue
    log "  marketplace add: $source"
    # shellcheck disable=SC2086
    if ! codex plugin marketplace add ${source} 2>/dev/null; then
      warn "  跳过或已存在: $source"
    fi
  done < <(read_lock_file "${REPO}/marketplaces.lock")

  log "安装 Plugin..."
  while IFS= read -r plugin; do
    [[ -z "$plugin" ]] && continue
    log "  plugin add: $plugin"
    if ! codex plugin add "$plugin" 2>/dev/null; then
      warn "  安装失败或已安装: $plugin"
    fi
  done < <(read_lock_file "${REPO}/plugins.lock")
else
  warn "当前 Codex 无 plugin 子命令（需要 >= 0.137），跳过 marketplace/plugin 恢复"
fi

echo ""
log "恢复完成！"
echo ""
echo "  改配置：编辑 ${REPO}/settings.json 后重新运行 bootstrap.sh"
echo "  启动：  codex"
echo ""
if [[ -n "${OPENAI_API_KEY:-}" ]]; then
  log "OPENAI_API_KEY 已就绪（长度 ${#OPENAI_API_KEY}）"
else
  warn "OPENAI_API_KEY 仍为空，Codex 可能无法调用模型"
fi
