#!/usr/bin/env bash
# 非 qz 环境：直连云豆，使用独立 Runtime/Home，不依赖 qz 映射或 qz CODEX_HOME。
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_ROOT="$(cd "$REPO/../.." && pwd)"
RUNTIME_DIR="${CODEX_DIRECT_RUNTIME:-$REPO/.runtime/direct}"
APP_DIR="$RUNTIME_DIR/app"
BIN_DIR="$RUNTIME_DIR/bin"
CODEX_HOME_DIR="$RUNTIME_DIR/home"
DIRECT_ENV="$REPO/direct_codex/codex.direct.env"
PERSONAL_ENV="$REPO/.env"
DIRECT_URL="${CODEX_DIRECT_BASE_URL:-https://yundou.ai/v1}"
CODEX_VERSION="${CODEX_VERSION:-0.155.1}"
mkdir -p "$APP_DIR" "$BIN_DIR" "$CODEX_HOME_DIR"

# 首次运行创建独立直连配置。优先：环境变量 > 根 .env > qz 密钥（仅同一共享项目存在时）。
if [[ ! -f "$DIRECT_ENV" ]]; then
  key="${CODEX_API_KEY:-${OPENAI_API_KEY:-}}"
  model="${CODEX_MODEL:-}"
  if [[ -f "$PERSONAL_ENV" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$PERSONAL_ENV"
    set +a
    key="${key:-${CODEX_API_KEY:-${OPENAI_API_KEY:-}}}"
  fi
  qz_env="$REPO/qz_codex/codex.api.env"
  if [[ -f "$qz_env" ]]; then
    [[ -n "$key" ]] || key="$(awk -F= '/^API_KEY=/{print substr($0,index($0,"=")+1)}' "$qz_env")"
    [[ -n "$model" ]] || model="$(awk -F= '/^MODEL=/{print substr($0,index($0,"=")+1)}' "$qz_env")"
  fi
  [[ -n "$key" ]] || {
    echo "缺少直连 API Key。请设置 CODEX_API_KEY，或在 $PERSONAL_ENV 中设置 CODEX_API_KEY。" >&2
    exit 1
  }
  printf '# 非 qz 直连配置（不要提交）\nBASE_URL=%s\nAPI_KEY=%s\nMODEL=%s\n' \
    "${DIRECT_URL%/}" "$key" "${model:-gpt-5.6}" > "$DIRECT_ENV"
  chmod 600 "$DIRECT_ENV"
fi

set -a
[[ -f "$PERSONAL_ENV" ]] && source "$PERSONAL_ENV"
source "$DIRECT_ENV"
set +a
[[ -n "${BASE_URL:-}" && -n "${API_KEY:-}" ]] || { echo "直连配置不完整: $DIRECT_ENV" >&2; exit 1; }

# 先验证直连接口。
python3 - "$BASE_URL" <<'PY'
import json, os, sys, urllib.request
base, key = sys.argv[1].rstrip('/'), os.environ['API_KEY']
req = urllib.request.Request(base + '/models', headers={'Authorization': 'Bearer ' + key})
try:
    with urllib.request.urlopen(req, timeout=30) as response:
        data = json.load(response)
    if response.status != 200 or not isinstance(data.get('data'), list):
        raise RuntimeError('模型列表响应异常')
except Exception as exc:
    print(f'直连 API 不可用: {base}: {exc}', file=sys.stderr)
    raise SystemExit(1)
PY

# 查找或安装真实 Codex。qz 共享项目中的二进制只作为可选复用，不共享 Home。
EXEC_A=""
EXEC_B=""
QZ_CLI_JS="$PROJECT_ROOT/apps/codex/offline/codex/package/bin/codex.js"
QZ_NODE="$PROJECT_ROOT/apps/node/bin/node"
if [[ -f "$QZ_CLI_JS" && -x "$QZ_NODE" ]]; then
  # 复用 qz 保存的 CLI 文件，但绕过 qz 包装器，避免覆盖 direct CODEX_HOME/API。
  EXEC_A="$QZ_NODE"
  EXEC_B="$QZ_CLI_JS"
elif [[ -x "$APP_DIR/node_modules/.bin/codex" ]]; then
  EXEC_A="$APP_DIR/node_modules/.bin/codex"
elif command -v npm >/dev/null 2>&1; then
  npm install --prefix "$APP_DIR" "@openai/codex@$CODEX_VERSION" >/dev/null
  EXEC_A="$APP_DIR/node_modules/.bin/codex"
else
  echo "未找到可复用 Codex，且系统没有 npm。请先安装 Node.js/npm。" >&2
  exit 1
fi

cat > "$BIN_DIR/codex" <<EOF
#!/usr/bin/env bash
set -euo pipefail
export CODEX_HOME="$CODEX_HOME_DIR"
for _env_file in "$PERSONAL_ENV" "$DIRECT_ENV"; do
  if [[ -f "\$_env_file" ]]; then
    set -a
    source "\$_env_file"
    set +a
  fi
done
[[ -n "\${API_KEY:-}" ]] && export OPENAI_API_KEY="\$API_KEY"
if [[ -n "$EXEC_B" ]]; then
  exec "$EXEC_A" "$EXEC_B" "\$@"
else
  exec "$EXEC_A" "\$@"
fi
EOF
chmod +x "$BIN_DIR/codex"

cat > "$CODEX_HOME_DIR/config.toml" <<EOF
# Generated by direct_codex/setup_direct_codex.sh
model = "${MODEL:-gpt-5.6}"
model_provider = "yundou"
model_reasoning_effort = "low"

[model_providers.yundou]
name = "Yundou"
base_url = "${BASE_URL%/}"
env_key = "OPENAI_API_KEY"
wire_api = "responses"
supports_websockets = false
request_max_retries = 3
stream_max_retries = 3
EOF
chmod 600 "$CODEX_HOME_DIR/config.toml"
printf 'direct\n' > "$CODEX_HOME_DIR/.deployment-mode"

# 公共个人配置同步到 direct Home。
CODEX_HOME="$CODEX_HOME_DIR" CODEX_BIN="$BIN_DIR/codex" \
  bash "$REPO/scripts/sync-personal-config.sh"

# 激活 direct 入口。真实数据和入口均位于仓库，不依赖个人目录。
mkdir -p "$REPO/.bin"
ln -sfn "$BIN_DIR/codex" "$REPO/.bin/codex"
ln -sfn "$BIN_DIR/codex" /usr/local/bin/codex 2>/dev/null || true
ln -sfn "$BIN_DIR/codex" /usr/bin/codex 2>/dev/null || true
if [[ -L "$HOME/.codex" || ! -e "$HOME/.codex" ]]; then
  ln -sfn "$CODEX_HOME_DIR" "$HOME/.codex" 2>/dev/null || true
fi

printf 'direct\n' > "$REPO/.active-mode"
echo "[OK] direct 模式已启用；CODEX_HOME=$CODEX_HOME_DIR"
